# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QueryBuilderPlugin
                                 A QGIS plugin
 Save your query in single plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-26
        copyright            : (C) 2024 by Philippine Statistics Authority | GMD
        email                : kedeleon.psagmd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QueryBuilderPlugin class from file QueryBuilderPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .query_builder_dialog import QueryBuilderPlugin
    return QueryBuilderPlugin(iface)
